[pytest]
testpaths = backend/tests
addopts =
    --strict-markers
    --cov=backend/app
    --cov-config=.coveragerc
    --cov-report=xml
    --cov-report=term-missing
markers =
    nowindows
    nolinux
    asyncio