sonar.projectKey=mjbobak_home-landing-app
sonar.organization=mjbobak


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=home-landing-app
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8

sonar.projectVersion = 0.1.0
sonar.sources = src/,Dockerfile,backend/app/
sonar.exclusions = docker-compose*.yml,src/__tests__/*,backend/tests/*,**/__pycache__/**,**/*.pyc,**/*.pyo,**/.venv/**,**/migrations/**,**/node_modules/**,**/dist/**,**/build/**,**/.next/**,**/.storybook/**,**/coverage/**,**/.git/**,**/.github/**
sonar.coverage.exclusions = docker-compose*.yml,src/__tests__/*,backend/tests/*,**/__pycache__/**,**/*.pyc,**/*.pyo,**/.venv/**,**/migrations/**,**/node_modules/**,**/dist/**,**/build/**,**/.next/**,**/.storybook/**,**/coverage/**,**/.git/**,**/.github/**
sonar.issue.ignore.multicriteria = s1
sonar.issue.ignore.multicriteria.s1.ruleKey = python:S1192,pythonsecurity:S5145
sonar.issue.ignore.multicriteria.s1.resourceKey = **/*.py
sonar.sourceEncoding = UTF-8

# Coverage report paths
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.python.coverage.reportPaths=coverage.xml
