"""initial_migration_with_budget_table

Revision ID: 7b52bcba7ec5
Revises:
Create Date: 2026-01-01 14:56:22.691774

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7b52bcba7ec5"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "budgets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("expense_type", sa.String(length=20), nullable=False, comment="ESSENTIAL or FUNSIES"),
        sa.Column(
            "expense_category",
            sa.String(length=100),
            nullable=False,
            comment="Category like CHILDREN, DAILY LIVING, etc.",
        ),
        sa.Column(
            "expense_label",
            sa.String(length=200),
            nullable=False,
            comment="Specific label like ALL THINGS DAISY, GROCERIES, etc.",
        ),
        sa.Column("budgeted", sa.Float(), nullable=False, comment="Budgeted amount for this category"),
        sa.Column("is_accrual", sa.Boolean(), nullable=False, comment="True for quarterly/annual items"),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="When this budget was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="When this budget was last updated",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_budgets_expense_category"), "budgets", ["expense_category"], unique=False)
    op.create_index(op.f("ix_budgets_expense_type"), "budgets", ["expense_type"], unique=False)
    op.create_index(op.f("ix_budgets_id"), "budgets", ["id"], unique=False)
    op.create_index("ix_budgets_type_category", "budgets", ["expense_type", "expense_category"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_budgets_type_category", table_name="budgets")
    op.drop_index(op.f("ix_budgets_id"), table_name="budgets")
    op.drop_index(op.f("ix_budgets_expense_type"), table_name="budgets")
    op.drop_index(op.f("ix_budgets_expense_category"), table_name="budgets")
    op.drop_table("budgets")
    # ### end Alembic commands ###
