"""add_expense_label_note_to_budgets

Revision ID: 7d28317fbfe1
Revises: 7b52bcba7ec5
Create Date: 2026-01-04 14:20:16.817000

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7d28317fbfe1"
down_revision: Union[str, None] = "7b52bcba7ec5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "budgets",
        sa.Column(
            "expense_label_note",
            sa.String(length=500),
            nullable=True,
            comment="Optional descriptive note for the expense label",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("budgets", "expense_label_note")
    # ### end Alembic commands ###
