// Mock budget data for development
import type { BudgetEntry } from '@/features/budget/types/budgetView';

export const mockBudgetData: BudgetEntry[] = [
  {
    id: 'BUD-0001',
    expenseType: 'ESSENTIAL',
    expenseCategory: 'CHILDREN',
    expenseLabel: 'ALL THINGS DAISY',
    budgeted: 400,
    spent: 380,
    remaining: 20,
    percentage: 95.0,
    isAccrual: false,
  },
  {
    id: 'BUD-0002',
    expenseType: 'ESSENTIAL',
    expenseCategory: 'CHILDREN',
    expenseLabel: 'DAY CARE',
    budgeted: 1500,
    spent: 1500,
    remaining: 0,
    percentage: 100.0,
    isAccrual: false,
  },
  {
    id: 'BUD-0003',
    expenseType: 'ESSENTIAL',
    expenseCategory: 'DAILY LIVING',
    expenseLabel: 'GROCERIES',
    budgeted: 1200,
    spent: 1150,
    remaining: 50,
    percentage: 95.8,
    isAccrual: false,
  },
  {
    id: 'BUD-0004',
    expenseType: 'ESSENTIAL',
    expenseCategory: 'DEBT OBLIGATIONS',
    expenseLabel: 'CAR LOAN',
    budgeted: 450,
    spent: 450,
    remaining: 0,
    percentage: 100.0,
    isAccrual: false,
  },
  {
    id: 'BUD-0005',
    expenseType: 'ESSENTIAL',
    expenseCategory: 'DEBT OBLIGATIONS',
    expenseLabel: 'FEES',
    budgeted: 100,
    spent: 85,
    remaining: 15,
    percentage: 85.0,
    isAccrual: false,
  },
  {
    id: 'BUD-0006',
    expenseType: 'ESSENTIAL',
    expenseCategory: 'DEBT OBLIGATIONS',
    expenseLabel: 'MORTGAGE',
    budgeted: 2500,
    spent: 2500,
    remaining: 0,
    percentage: 100.0,
    isAccrual: false,
  },
  {
    id: 'BUD-0007',
    expenseType: 'FUNSIES',
    expenseCategory: 'ENTERAINMENT',
    expenseLabel: 'DAISY ACTIVITIES',
    budgeted: 200,
    spent: 185,
    remaining: 15,
    percentage: 92.5,
    isAccrual: false,
  },
  {
    id: 'BUD-0008',
    expenseType: 'FUNSIES',
    expenseCategory: 'ENTERAINMENT',
    expenseLabel: 'MEMBERSHIPS',
    budgeted: 150,
    spent: 150,
    remaining: 0,
    percentage: 100.0,
    isAccrual: false,
  },
  {
    id: 'BUD-0009',
    expenseType: 'FUNSIES',
    expenseCategory: 'ENTERTAINMENT & SUBSCRIPTIONS',
    expenseLabel: 'SUB - AMAZON PRIME',
    budgeted: 15,
    spent: 15,
    remaining: 0,
    percentage: 100.0,
    isAccrual: false,
  },
  {
    id: 'BUD-0010',
    expenseType: 'FUNSIES',
    expenseCategory: 'ENTERTAINMENT & SUBSCRIPTIONS',
    expenseLabel: 'SUB - APPLE CARE IPHONE',
    budgeted: 10,
    spent: 10,
    remaining: 0,
    percentage: 100.0,
    isAccrual: false,
  },
  {
    id: 'BUD-0011',
    expenseType: 'FUNSIES',
    expenseCategory: 'ENTERTAINMENT & SUBSCRIPTIONS',
    expenseLabel: 'SUB - APPLE FAMILY PLAN',
    budgeted: 20,
    spent: 20,
    remaining: 0,
    percentage: 100.0,
    isAccrual: false,
  },
  {
    id: 'BUD-0012',
    expenseType: 'FUNSIES',
    expenseCategory: 'ENTERTAINMENT & SUBSCRIPTIONS',
    expenseLabel: 'SUB - COSTCO',
    budgeted: 10,
    spent: 10,
    remaining: 0,
    percentage: 100.0,
    isAccrual: false,
  },
  {
    id: 'BUD-0013',
    expenseType: 'FUNSIES',
    expenseCategory: 'ENTERTAINMENT & SUBSCRIPTIONS',
    expenseLabel: 'SUB - DISNEY+',
    budgeted: 12,
    spent: 12,
    remaining: 0,
    percentage: 100.0,
    isAccrual: false,
  },
  {
    id: 'BUD-0014',
    expenseType: 'FUNSIES',
    expenseCategory: 'ENTERTAINMENT & SUBSCRIPTIONS',
    expenseLabel: 'SUB - NETFLIX',
    budgeted: 18,
    spent: 18,
    remaining: 0,
    percentage: 100.0,
    isAccrual: false,
  },
  {
    id: 'BUD-0015',
    expenseType: 'FUNSIES',
    expenseCategory: 'ENTERTAINMENT & SUBSCRIPTIONS',
    expenseLabel: 'SUB - TESLA NAVIGATION',
    budgeted: 10,
    spent: 10,
    remaining: 0,
    percentage: 100.0,
    isAccrual: false,
  },
  {
    id: 'BUD-0016',
    expenseType: 'FUNSIES',
    expenseCategory: 'ENTERTAINMENT & SUBSCRIPTIONS',
    expenseLabel: 'SUB - YOUTUBE PREMIUM',
    budgeted: 12,
    spent: 12,
    remaining: 0,
    percentage: 100.0,
    isAccrual: false,
  },
  {
    id: 'BUD-0017',
    expenseType: 'FUNSIES',
    expenseCategory: 'FLEXIBLE FAMILY SPENDING',
    expenseLabel: 'BABYSITTING',
    budgeted: 200,
    spent: 180,
    remaining: 20,
    percentage: 90.0,
    isAccrual: false,
  },
  {
    id: 'BUD-0018',
    expenseType: 'FUNSIES',
    expenseCategory: 'FLEXIBLE FAMILY SPENDING',
    expenseLabel: 'CLEANING SERVICE',
    budgeted: 300,
    spent: 300,
    remaining: 0,
    percentage: 100.0,
    isAccrual: false,
  },
  {
    id: 'BUD-0019',
    expenseType: 'FUNSIES',
    expenseCategory: 'FLEXIBLE FAMILY SPENDING',
    expenseLabel: 'FOOD & DRINK',
    budgeted: 400,
    spent: 425,
    remaining: -25,
    percentage: 106.3,
    isAccrual: false,
  },
  {
    id: 'BUD-0020',
    expenseType: 'FUNSIES',
    expenseCategory: 'FLEXIBLE FAMILY SPENDING',
    expenseLabel: 'GIFTS',
    budgeted: 250,
    spent: 280,
    remaining: -30,
    percentage: 112.0,
    isAccrual: false,
  },
  {
    id: 'BUD-0021',
    expenseType: 'FUNSIES',
    expenseCategory: 'FLEXIBLE FAMILY SPENDING',
    expenseLabel: 'HOME SHOPPING',
    budgeted: 300,
    spent: 275,
    remaining: 25,
    percentage: 91.7,
    isAccrual: false,
  },
  {
    id: 'BUD-0022',
    expenseType: 'FUNSIES',
    expenseCategory: 'FLEXIBLE FAMILY SPENDING',
    expenseLabel: 'TRAVEL',
    budgeted: 800,
    spent: 650,
    remaining: 150,
    percentage: 81.3,
    isAccrual: false,
  },
  {
    id: 'BUD-0023',
    expenseType: 'FUNSIES',
    expenseCategory: 'FLEXIBLE FAMILY SPENDING',
    expenseLabel: 'WEDDINGS',
    budgeted: 500,
    spent: 450,
    remaining: 50,
    percentage: 90.0,
    isAccrual: false,
  },
  {
    id: 'BUD-0024',
    expenseType: 'FUNSIES',
    expenseCategory: 'FLEXIBLE PERSONAL SPENDING',
    expenseLabel: 'ANGELA',
    budgeted: 300,
    spent: 285,
    remaining: 15,
    percentage: 95.0,
    isAccrual: false,
  },
  {
    id: 'BUD-0025',
    expenseType: 'FUNSIES',
    expenseCategory: 'FLEXIBLE PERSONAL SPENDING',
    expenseLabel: 'MARTY',
    budgeted: 300,
    spent: 290,
    remaining: 10,
    percentage: 96.7,
    isAccrual: false,
  },
  {
    id: 'BUD-0026',
    expenseType: 'FUNSIES',
    expenseCategory: 'HEALTH',
    expenseLabel: 'HEALTH & WELLNESS',
    budgeted: 250,
    spent: 180,
    remaining: 70,
    percentage: 72.0,
    isAccrual: false,
  },
  {
    id: 'BUD-0027',
    expenseType: 'FUNSIES',
    expenseCategory: 'INVESTMENTS',
    expenseLabel: '529A',
    budgeted: 500,
    spent: 500,
    remaining: 0,
    percentage: 100.0,
    isAccrual: false,
  },
  {
    id: 'BUD-0028',
    expenseType: 'FUNSIES',
    expenseCategory: 'INVESTMENTS',
    expenseLabel: 'ADDITIONAL MORTGAGE PAYMENT',
    budgeted: 1000,
    spent: 1000,
    remaining: 0,
    percentage: 100.0,
    isAccrual: false,
  },
  {
    id: 'BUD-0029',
    expenseType: 'ESSENTIAL',
    expenseCategory: 'PERSONAL ESCROW',
    expenseLabel: 'CAR INSURANCE',
    budgeted: 200,
    spent: 200,
    remaining: 0,
    percentage: 100.0,
    isAccrual: false,
  },
  {
    id: 'BUD-0030',
    expenseType: 'ESSENTIAL',
    expenseCategory: 'PERSONAL ESCROW',
    expenseLabel: 'HOME INSURANCE',
    budgeted: 150,
    spent: 150,
    remaining: 0,
    percentage: 100.0,
    isAccrual: false,
  },
  {
    id: 'BUD-0031',
    expenseType: 'ESSENTIAL',
    expenseCategory: 'PERSONAL ESCROW',
    expenseLabel: 'PROPERTY TAXES',
    budgeted: 600,
    spent: 600,
    remaining: 0,
    percentage: 100.0,
    isAccrual: false,
  },
  {
    id: 'BUD-0032',
    expenseType: 'ESSENTIAL',
    expenseCategory: 'RESERVES',
    expenseLabel: 'RESERVES',
    budgeted: 1000,
    spent: 1000,
    remaining: 0,
    percentage: 100.0,
    isAccrual: false,
  },
  {
    id: 'BUD-0033',
    expenseType: 'ESSENTIAL',
    expenseCategory: 'TRANSPORTATION',
    expenseLabel: 'GAS',
    budgeted: 300,
    spent: 280,
    remaining: 20,
    percentage: 93.3,
    isAccrual: false,
  },
  {
    id: 'BUD-0034',
    expenseType: 'ESSENTIAL',
    expenseCategory: 'TRANSPORTATION',
    expenseLabel: 'VEHICLE REGISTRATION',
    budgeted: 100,
    spent: 95,
    remaining: 5,
    percentage: 95.0,
    isAccrual: false,
  },
  {
    id: 'BUD-0035',
    expenseType: 'ESSENTIAL',
    expenseCategory: 'TRANSPORTATION',
    expenseLabel: 'WORK TRANSPORTATION',
    budgeted: 200,
    spent: 185,
    remaining: 15,
    percentage: 92.5,
    isAccrual: false,
  },
  {
    id: 'BUD-0036',
    expenseType: 'ESSENTIAL',
    expenseCategory: 'UTILITY',
    expenseLabel: 'UTILS - ELECTRICITY',
    budgeted: 150,
    spent: 145,
    remaining: 5,
    percentage: 96.7,
    isAccrual: false,
  },
  {
    id: 'BUD-0037',
    expenseType: 'ESSENTIAL',
    expenseCategory: 'UTILITY',
    expenseLabel: 'UTILS - GAS',
    budgeted: 80,
    spent: 75,
    remaining: 5,
    percentage: 93.8,
    isAccrual: false,
  },
  {
    id: 'BUD-0038',
    expenseType: 'ESSENTIAL',
    expenseCategory: 'UTILITY',
    expenseLabel: 'UTILS - INTERNET',
    budgeted: 100,
    spent: 100,
    remaining: 0,
    percentage: 100.0,
    isAccrual: false,
  },
  {
    id: 'BUD-0039',
    expenseType: 'ESSENTIAL',
    expenseCategory: 'UTILITY',
    expenseLabel: 'UTILS - PHONE',
    budgeted: 120,
    spent: 120,
    remaining: 0,
    percentage: 100.0,
    isAccrual: false,
  },
  {
    id: 'BUD-0040',
    expenseType: 'ESSENTIAL',
    expenseCategory: 'UTILITY',
    expenseLabel: 'UTILS - TRASH',
    budgeted: 50,
    spent: 50,
    remaining: 0,
    percentage: 100.0,
    isAccrual: false,
  },
  {
    id: 'BUD-0041',
    expenseType: 'ESSENTIAL',
    expenseCategory: 'UTILITY',
    expenseLabel: 'UTILS - WATER/SEWER',
    budgeted: 90,
    spent: 85,
    remaining: 5,
    percentage: 94.4,
    isAccrual: false,
  },
];
